export const CATEGORY_FETCH_LOADING = "CATEGORY_FETCH_LOADING";
export const CATEGORY_FETCH_MESSAGE = "CATEGORY_FETCH_MESSAGE";
export const CATEGORY_FETCH_ALL = "CATEGORY_FETCH_ALL";
export const CATEGORY_FETCH_SINGLE = "CATEGORY_FETCH_SINGLE";
export const CATEGORY_FETCH_ERROR = "CATEGORY_FETCH_ERROR";
export const CATEGORY_CLEAR_STATE = "CATEGORY_CLEAR_STATE";
