export const SONG_FETCH_LOADING = "SONG_FETCH_LOADING";
export const SONG_FETCH_MESSAGE = "SONG_FETCH_MESSAGE";
export const SONG_FETCH_ALL = "SONG_FETCH_ALL";
export const SONG_FETCH_SINGLE = "SONG_FETCH_SINGLE";
export const SONG_FETCH_ERROR = "SONG_FETCH_ERROR";
export const SONG_CLEAR_STATE = "SONG_CLEAR_STATE";
