export const ARTIST_FETCH_LOADING = "ARTIST_FETCH_LOADING";
export const ARTIST_FETCH_MESSAGE = "ARTIST_FETCH_MESSAGE";
export const ARTIST_FETCH_ALL = "ARTIST_FETCH_ALL";
export const ARTIST_FETCH_SINGLE = "ARTIST_FETCH_SINGLE";
export const ARTIST_FETCH_ERROR = "ARTIST_FETCH_ERROR";
export const ARTIST_CLEAR_STATE = "ARTIST_CLEAR_STATE";
